# Generated by Django 2.0.7 on 2018-07-21 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_bio', models.TextField()),
                ('profile_birthday', models.DateTimeField()),
                ('profile_home_town', models.CharField(max_length=255)),
                ('profile_hobbies', models.TextField()),
                ('profile_favorite_genre', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bio', to='logReg.User')),
            ],
        ),
    ]
