# Generated by Django 2.0.7 on 2018-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='profile_bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile_birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile_favorite_genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile_hobbies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='profile_home_town',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
