# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 14:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 9, 19, 15, 684000)),
        ),
    ]
