# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 14:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180720_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 9, 20, 1, 996000)),
        ),
        migrations.AlterField(
            model_name='thought',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 9, 20, 1, 996000)),
        ),
    ]
