# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180720_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
